### ISSUE TITLE
"Disconnected from server" when retrieving from WC

### ISSUE THREAD

**Issue by sashafr** [jladams/stackr#1]
I've set up an instance of Stackr following the instructions, and uploaded some our data, but when I click Get WC Holdings, it seems to start working (loading bar in lower right gets about halfway through) and the I get the Disconnected from server message. You can see our site here: http://134.209.124.12:3838/stackr/#section-data

Any idea what might be causing it?

**Comment by jladams** [comment]
That's a notice from Shiny/Shiny Server rather than stackR, so it could be a few things - is there anything showing up in your logs? 

You can see where to check those here: [https://docs.rstudio.com/shiny-server/#logging-and-analytics](https://docs.rstudio.com/shiny-server/#logging-and-analytics)

**Comment by sashafr** [comment]
Ah thank you! Haven't used Shiny before and thought the warning was part of your application. This is the error I was getting (in case anyone has the problem):

```Warning in dir.create("./data/wc") :
  cannot create dir './data/wc', reason 'Permission denied'
```
So I just had to set the permissions for my shiny server user to allow writing to that directory and restart it.

I suppose I should probably not tag this on to this issue since its a different question, but now that it completed, I'm getting -1 in the wc_holdings column for everything. Does that just indicate a connection issue? Or something wrong with my data?

**Comment by jladams** [comment]
Glad that fixed it! I'll update documentation to reflect the permissions Shiny will need. 

As for the -1, that's expected behavior. It's a placeholder signifying that a record either hasn't been checked against WorldCat or that WorldCat didn't return a valid count (I'll also update documentation about this).

**Comment by jladams** [comment]
Documentation has now been updated.
